import type { Metadata } from "next";
import { Inter, Oswald } from "next/font/google";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import LibraryContextProvider from "./context/LibraryContextProvider";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const res = await fetch("https://api.abcz.workers.dev/api/fitlog");
  const libraries = await res.json();

  return (
    <html
      lang="en"
      data-theme="light"
      className={`${inter.variable} ${oswald.variable} h-full antialiased font-inter`}
    >
      <body className="min-h-full flex flex-col bg-black text-white">
        <LibraryContextProvider libraries={libraries}>
          <Navbar />
          <main className="flex-1 w-[95%] mx-auto lg:w-[85%] md:w-[85%]  my-10">
            {children}
          </main>
          <Footer />
        </LibraryContextProvider>
      </body>
    </html>
  );
}
